# Generated by Django 6.1 on 2026-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
